### ISSUE TITLE
Great work guys! Some suggestions for the table

### ISSUE THREAD

**Issue by ivank** [ovotech/shipit#31]
Just saw this service today and want to help it out if I can. I have a couple of small suggestions for the lovely table, hope they are useful:

- [x] timestamp is great that its shown "distance in time" but actual date is also important, maybe add it as a tooltip?
- [ ] "Teams" is a small pool of data, so you could make it an icon? Maybe have a "team page" to be linked to with name, links contacts etc, and have the row in the table only show an icon?
- [ ] "build number" is wildly uneven, you could limit it up to a certain width, and put everything else behind an "..." e.g. instead of `2018-08-09.0b417650bbbe1899fe4edc2adf18c0a1f0ba4659` you could have `2018-08-09.0b417...` and the full length can be shown on hover with tooltip or something
- [ ] Links can be the services logos - a lot more recognisable and takes way less space
- [ ] Maybe do some text processing on the "release notes" right now they are just the raw commit, maybe strip down the technical fields and leave only the text, or even better, do what GitHub are doing and show only the title with the full commit message shown on click.

**Comment by cb372** [comment]
Thanks for the ideas.

Regarding the first one, the absolute timestamp should already be a tooltip. If it's not, that's a bug.

But I often find myself wanting to see the actual timestamps, so maybe a button to toggle between displaying the relative and absolute timestamps would be useful?

**Comment by ivank** [comment]
Well there's enough place to show both - `12 Feb 2018 12:20 (12 days ago)` or something.

**Comment by lukebriscoe** [comment]
@ivank do you fancy having a go at raising a PR for a few of those suggestions yourself? We're keen to get more people involved with making improvements  😄

**Comment by ivank** [comment]
Sadly scala is hardly my strong suit - I'm more of a NodeJS dev. I could potentially help you guys out with the html, but that's it.

**Comment by cb372** [comment]
I think most of these can be fixed with small HTML/CSS tweaks. Happy to pair on it sometime. Maybe next week?
