### ISSUE TITLE
API to integrate with shipit

### ISSUE THREAD

**Issue by emilyryatt** [ovotech/shipit#39]
I would like to be able to pull information about the N latest deployments for a given team for my incredible dashboarding skills

**Comment by mwz** [comment]
Yes, this would be very useful for the Super Tech Dashboard project.

**Comment by cb372** [comment]
This is totally do-able, but did you know shipit sends all deployments to Datadog? It might make sense to get the data from there.

**Comment by robertmackenzie** [comment]
OVO is no longer maintaining Shipit.
