### ISSUE TITLE
Allow custom notes

### ISSUE THREAD

**Issue by olmesm** [ovotech/shipit#89]
Any chance we could attach custom notes?

We're running a nightly build and it would be great if instead of the standard 

```
Service [<team>/<repo>] was deployed successfully.
```

We need to have a custom message for more relevant status.

We could also prefix with `[custom message]` in data dog to not mess with analytics (if needed)

**Comment by cb372** [comment]
I'm a bit confused regarding what you mean by "nightly build". Do you mean you are deploying a new version of a service every night, or does your build do something else?

What would an example of your custom message look like?
